Int.add_v0 5 = Test.derrorMessage
  "Int.add has 0 type parameters and 2 parameters, but here was called with 0 type arguments and 1 arguments."

// TODO - not yet suppported
// (let fn = (fun x -> x + 1)
//  fn 6) = 7

// ---------------------------
// DarkInternal tests are internal
// ---------------------------
module Darkinternal =
  (let _ = Test.setExpectedExceptionCount 1 in
   DarkInternal.Infra.SchedulingRule.list ()) = Test.derrorMessage "Unknown error"

// ---------------------------
// User-defined Functions
// Should match packages/darklang/test/test.dark
// ---------------------------

module UserDefined =

  let stringFn (key: String) : String = key ++ " appended string"

  let fnWithTypeArgAndOneParam<'a> (arg: 'a) : 'a = arg

  let twoStringFn (str1: String) (str2: String) : String =
    str1 ++ " appended " ++ str2

  let returnsInt () : Int = 5

  let returnsString () : String = "string"

  let returnsOptionSome () : PACKAGE.Darklang.Stdlib.Option.Option<Int> =
    PACKAGE.Darklang.Stdlib.Option.Option.Some 5

  let returnsOptionNone () : PACKAGE.Darklang.Stdlib.Option.Option<Int> =
    PACKAGE.Darklang.Stdlib.Option.Option.None

  let returnsResultOk () : PACKAGE.Darklang.Stdlib.Result.Result<Int, 'err> =
    PACKAGE.Darklang.Stdlib.Result.Result.Ok 5

  let returnsResultError () : PACKAGE.Darklang.Stdlib.Result.Result<String, Bool> =
    PACKAGE.Darklang.Stdlib.Result.Result.Error false

  let throwsException () : 'a =
    Test.raiseException "throwsException message"

  let derrorFn (msg: String) : String = msg ++ Test.runtimeError msg

  let fnWithTypeArgs<'a, 'b> (a: 'a) (b: 'b) : 'a = a

  let fnWithTypedReturn<'a> () : 'a = 5 // errors unless Int passed for 'a

  type X<'a> =
    | A of Int
    | B of 'a

  let polyFn (a: X<'a>) : X<'a> = a
  let strFn (a: X<String>) : X<String> = a
  let definedPolyFn<'a> (a: X<'a>) : X<'a> = a



  stringFn "string" = "string appended string"
  twoStringFn "str1" "str2" = "str1 appended str2"
  returnsInt () = 5
  returnsString () = "string"
  returnsOptionSome () = PACKAGE.Darklang.Stdlib.Option.Option.Some 5
  (returnsOptionSome ()) |> unwrap = 5
  returnsOptionNone () = PACKAGE.Darklang.Stdlib.Option.Option.None
  returnsResultOk () = PACKAGE.Darklang.Stdlib.Result.Result.Ok 5
  (returnsResultOk ()) |> unwrap = 5
  fnWithTypeArgAndOneParam<Int> 1 = 1
  fnWithTypeArgs<Int, String> 5 "x" = 5
  fnWithTypedReturn<Int> () = 5

  polyFn (X.A 5) = X.A 5
  polyFn (X.B "str") = X.B "str"

  strFn (X.A 5) = strFn (X.A 5)
  strFn (X.B "str") = X.B "str"

  // TYPESCLEANUP - support userFn declaration with type arguments
  // definedPolyFn<String>(A.A 5) = definedPolyFn (A.A 5)
  // definedPolyFn<String>(A.B "str") = definedPolyFn (A.B "str")



  module InvalidFnCalls =
    functionWhichDoesntExist 6 = Test.derrorMessage
      "There is no function named functionWhichDoesntExist"

    stringFn 5 = Test.derrorMessage
      "UserDefined.stringFn's 1st argument (`key`) should be an String. However, an Int (5) was passed instead.\n\nExpected: (key: String)\nActual: an Int: 5"

    stringFn "str1" "str2" = Test.derrorMessage
      "UserDefined.stringFn has 0 type parameters and 1 parameters, but here was called with 0 type arguments and 2 arguments."

    fnWithTypeArgAndOneParam 1 = Test.derrorMessage
      "UserDefined.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 0 type arguments and 1 arguments."

    fnWithTypeArgAndOneParam<Int> 1 "str2" = Test.derrorMessage
      "UserDefined.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 1 type arguments and 2 arguments."

    fnWithTypeArgAndOneParam<Int, String> 1 = Test.derrorMessage
      "UserDefined.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 2 type arguments and 1 arguments."

    fnWithTypeArgAndOneParam<Int, String> 1 "str" = Test.derrorMessage
      "UserDefined.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 2 type arguments and 2 arguments."

    fnWithTypeArgAndOneParam<Int> "str2" = Test.derrorMessage
      "UserDefined.fnWithTypeArgAndOneParam's 1st argument (`arg`) should be an Int. However, an String (\"str2\") was passed instead.\n\nExpected: (arg: 'a)\nActual: an String: \"str2\""

    fnWithTypedReturn<String> () = Test.derrorMessage
      "UserDefined.fnWithTypedReturn's return value should be an String. However, an Int (5) was passed instead.\n\nExpected: 'a\nActual: an Int: 5"

    (let _ = Test.setExpectedExceptionCount 1 in throwsException ()) = Test.derrorMessage
      "Unknown error"

    derrorFn "msg" = Test.derrorMessage "msg"


// ---------------------------
// Package manager function calls
// Uses functions/types from packages/darklang/test/test.dark
// ---------------------------
module Packages =
  PACKAGE.Darklang.Test.stringFn "string" = "string appended string"
  PACKAGE.Darklang.Test.twoStringFn "str1" "str2" = "str1 appended str2"
  PACKAGE.Darklang.Test.returnsInt () = 5
  PACKAGE.Darklang.Test.returnsString () = "string"

  PACKAGE.Darklang.Test.returnsOptionSome () = PACKAGE.Darklang.Stdlib.Option.Option.Some
    5

  (PACKAGE.Darklang.Test.returnsOptionSome ()) |> unwrap = 5
  PACKAGE.Darklang.Test.returnsOptionNone () = PACKAGE.Darklang.Stdlib.Option.Option.None

  PACKAGE.Darklang.Test.returnsResultOk () = PACKAGE.Darklang.Stdlib.Result.Result.Ok
    5

  (PACKAGE.Darklang.Test.returnsResultOk ()) |> unwrap = 5

  PACKAGE.Darklang.Test.returnsResultError () = PACKAGE.Darklang.Stdlib.Result.Result.Error
    false

  PACKAGE.Darklang.Test.polyFn (PACKAGE.Darklang.Test.X.A 5) = PACKAGE.Darklang.Test.X.A
    5

  PACKAGE.Darklang.Test.polyFn (PACKAGE.Darklang.Test.X.B "str") = PACKAGE.Darklang.Test.X.B
    "str"

  PACKAGE.Darklang.Test.strFn (PACKAGE.Darklang.Test.X.A 5) = PACKAGE
    .Darklang
    .Test
    .strFn (PACKAGE.Darklang.Test.X.A 5)

  PACKAGE.Darklang.Test.strFn (PACKAGE.Darklang.Test.X.B "str") = PACKAGE.Darklang.Test.X.B
    "str"

  // TYPESCLEANUP - support packageFn declaration with type arguments
  // PACKAGE.Darklang.Test.definedPolyFn<String>(X.A 5) = PACKAGE.Darklang.Test.definedPolyFn (X.A 5)
  // PACKAGE.Darklang.Test.definedPolyFn<String>(X.B "str") = PACKAGE.Darklang.Test.definedPolyFn (X.B "str")



  module Invalid =
    PACKAGE.Darklang.Test.stringFn 5 = Test.derrorMessage
      "PACKAGE.Darklang.Test.stringFn's 1st argument (`key`) should be an String. However, an Int (5) was passed instead.\n\nExpected: (key: String)\nActual: an Int: 5"

    PACKAGE.Darklang.Test.stringFn "str1" "str2" = Test.derrorMessage
      "PACKAGE.Darklang.Test.stringFn has 0 type parameters and 1 parameters, but here was called with 0 type arguments and 2 arguments."

    PACKAGE.Darklang.Test.derrorFn "test" = Test.derrorMessage "test"

    (let _ = Test.setExpectedExceptionCount 1 in
     PACKAGE.Darklang.Test.throwsException ()) = Test.derrorMessage "Unknown error"

    PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam 1 = Test.derrorMessage
      "PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 0 type arguments and 1 arguments."

    PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam<Int> 1 "str2" = Test.derrorMessage
      "PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 1 type arguments and 2 arguments."

    PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam<Int, String> 1 = Test.derrorMessage
      "PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 2 type arguments and 1 arguments."

    PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam<Int, String> 1 "str" = Test.derrorMessage
      "PACKAGE.Darklang.Test.fnWithTypeArgAndOneParam has 1 type parameters and 1 parameters, but here was called with 2 type arguments and 2 arguments."